### ISSUE TITLE
Consider UI tweaks

### ISSUE THREAD

**Issue by katamartin** [carbonplan/compliance-users#11]
####  Navigation and linking
I find myself wanting to go “back” to previous search results (e.g. if I search for a project and select a particular user ID, I’d prefer to be able to use browser navigation to go back to view that project rather than have to search again for that project for find that project ID in the results for the user ID).

The search state could be moved to be driven off of query params to do this.

Alternatively, another thing that strikes me is that the right side of the page is really only populated when a particular project/user/facility is selected so each set of “results” is really just a view into that project/user/facility. To me, this means that routes like `/projects/[id]` could make sense here.

#### Results view
There is something sort of funny to me about the relationship between the first row of the table and the rest of the results. It is distinct from the other rows and not counted towards the results total. It seems like color is doing a lot of the work to make this entry feel distinct and I wonder if it would be clarifying to do more? It could be worth trying to pull out into table heading or above the results table. This might also agree well with the idea above that each set of results is actually a specific project/user/facility view.

### Detailed feedback
| Note      | Screenshot |
| ----------- | ----------- |
| Only the arrow is clickable in the user/project ID table row -- possible to use Link to make the entire thing clickable? |   <img width="227" alt="Screen Shot 2021-12-06 at 9 10 59 AM" src="https://user-images.githubusercontent.com/12436887/144890690-dee4442d-310e-4187-94ec-78bdb59a75fc.png">   |
| Once you’ve clicked on a search result, the Input loses focus and gets populated with the search result name. In this state, it almost feels like the input has “disappeared.” I wonder if an “X” icon or a search icon next to the input would help. | <img width="741" alt="Screen Shot 2021-12-06 at 8 42 47 AM" src="https://user-images.githubusercontent.com/12436887/144890794-1971f417-824b-49c0-a709-74788413cd5d.png"> |
| We should scroll to the top of the page on "navigation" | |

**Comment by freeman-lab** [comment]
This should be addressed by the major reworking in https://github.com/carbonplan/compliance-users/commit/d1dc52ed49288241ded7c1be62bd7a2ee476ff60. Great suggestions, thanks again!
